# NEUROSPHERE CORE CONFIGURATION
FOUNDER_ID = "TM-GEN-F69870"
SYSTEM_STATUS = "VALID_MAINNET" # Ubah ke "SIMULATION" jika ingin demo
STABLE_COIN_SYMBOL = "IND-EUR"
TOTAL_ENPE_SUPPLY = 100000000000000 # 100 Triliun

def check_status():
    if SYSTEM_STATUS == "VALID_MAINNET":
        print(">>> STATUS: ONLINE - NEUROSPHERE MAINNET (AUTHENTIC)")
    else:
        print(">>> STATUS: OFFLINE - SIMULATION MODE")

